version: "3.9"

services:
  server:
    image: carlasim/carla:0.9.13
    entrypoint: [ "/bin/bash", "/home/carla/CarlaUE4.sh" ]
    command:
      [
        "-RenderOffscreen",
        "-carla-rpc-port=${CARLA_SERVER_PORT:-2000}",
        "-carla-streaming-port=${CARLA_SERVER_STREAMING_PORT:-2001}",
        "-quality-level=Epic"
      ]
    expose:
      - "${CARLA_SERVER_PORT:-2000}-${CARLA_SERVER_STREAMING_PORT_2:-2002}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,graphics,utility
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '${CARLA_SERVER_GPU_ID:-0}' ]
              capabilities: [ 'compute', 'graphics', 'utility' ]
